# This yaml brings up node agent as a DaemonSet, which takes FlexVolume driver connection.
# A detailed tutorial will be added soon.
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nodeagent
spec:
  template:
    metadata:
      labels:
        app: nodeagent
        version: v1
    spec:
      containers:
      - name: nodeagent
        image: $HUB/node-agent-k8s:$TAG
        imagePullPolicy: IfNotPresent
